# Your Name or Company
title: Mara Montanari

# Description of your website. This is used for social sharing.
description:  Doces para festas e comemorações. 

# A brief blurb about yourself
content: Doces para festas e comemorações: brigadeiro, bolo, bolo de pote, tortas e sobremesas. Personalize sua encomenda ao entrar em contato.

# Add your social links
social:
  - platform: facebook
    url: https://facebook.com/#
  - platform: instagram
    url: https://instagram.com/#
  - platform: whatsapp
    url: https://api.whatsapp.com/send?phone=5519997450298&text=whatsapp

# General settings
# url: http://brianmaierjr.github.com/uni
# baseurl: "/uni" 
markdown: kramdown
sharing_image: share.jpg
# google_analytics: 

#### LAYOUT OPTIONS #####

# Half layout
half_side: right

# Full layout
# full_text_position: right # left, right or center
